export const SCHEMA = {
    AWARDPLAYER: 'awardplayers',
    AWARDTEAM: 'awardteams',
    CARD: 'cards',
    COACH: 'coaches',
    GOAL: 'goals',
    MATCH: 'matches',
    PLAYER: 'players',
    PRIZE: 'prizes',
    REFEREE: 'referees',
    ROUND: 'rounds',
    SPONSOR: 'sponsors',
    STADIUM: 'stadiums',
    STATISTICALPLAYER: 'statisticalplayers',
    STATISTICALTEAM: 'statisticalteams',
    TABLE: 'tables',
    TEAM: 'teams',
    TOURNAMENT: 'tournaments',
    USER: 'users',
};
